@echo off
REM Generated by wrapper
set DIRNAME=%~dp0
REM Run with classpath if the jar does not contain a Main-Class entry
java -Dmaven.multiModuleProjectDirectory="%DIRNAME%" -cp "%DIRNAME%\.mvn\wrapper\maven-wrapper.jar" org.apache.maven.wrapper.MavenWrapperMain %*
