@echo off
REM Generated by wrapper
set DIRNAME=%~dp0
REM Remove trailing backslash from DIRNAME to avoid escaping closing quote
if "%DIRNAME:~-1%"=="\" set DIRNAME=%DIRNAME:~0,-1%
REM Run with classpath if the jar does not contain a Main-Class entry
java -Dmaven.multiModuleProjectDirectory="%DIRNAME%" -cp "%DIRNAME%\.mvn\wrapper\maven-wrapper.jar" org.apache.maven.wrapper.MavenWrapperMain %*
